package org.cgiar.ccafs.marlo.data.model;
// Generated Sep 8, 2017 2:12:52 PM by Hibernate Tools 5.2.5.Final


/**
 * CrpsAgreement generated by hbm2java
 */
public class CrpAgreement implements java.io.Serializable {


  private Long id;
  private Agreement agreement;
  private String crpId;
  private String description;
  private Double percentage;

  public CrpAgreement() {
  }


  public CrpAgreement(Agreement agreement, String crpId, String description) {
    this.agreement = agreement;
    this.crpId = crpId;
    this.description = description;
  }

  public CrpAgreement(Agreement agreement, String crpId, String description, Double percentage) {
    this.agreement = agreement;
    this.crpId = crpId;
    this.description = description;
    this.percentage = percentage;
  }

  public Agreement getAgreement() {
    return this.agreement;
  }

  public String getCrpId() {
    return this.crpId;
  }

  public String getDescription() {
    return this.description;
  }

  public Long getId() {
    return this.id;
  }

  public Double getPercentage() {
    return this.percentage;
  }

  public void setAgreement(Agreement agreement) {
    this.agreement = agreement;
  }

  public void setCrpId(String crpId) {
    this.crpId = crpId;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setPercentage(Double percentage) {
    this.percentage = percentage;
  }


}

